import{a as S,S as q,i as u}from"./assets/vendor-BjRz3xa9.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const n of o.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&a(n)}).observe(document,{childList:!0,subtree:!0});function s(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function a(e){if(e.ep)return;e.ep=!0;const o=s(e);fetch(e.href,o)}})();const P="49730830-c57beb55a0f893ff92d6370c6",d=15;async function m(r,t=1){const{data:s}=await S.get("https://pixabay.com/api/",{params:{key:P,q:r,image_type:"photo",orientation:"horizontal",safesearch:"true",page:t,per_page:d}});return s}const h=document.querySelector(".gallery"),g=document.querySelector(".loader"),f=document.querySelector(".load-more");let M=new q(".gallery a");function $(r){const t=r.map(({webformatURL:s,largeImageURL:a,tags:e,likes:o,views:n,comments:w,downloads:v})=>`<li class="gallery-item">
        <a href="${a}" class="gallery-link"><img class="gallery-img" src="${s}" alt="${e}"/>
        <div class="rectangle">
        <p class="card-value"><b>Likes</b>: ${o}</p>
        <p class="card-value"><b>Views</b>: ${n}</p>
        <p class="card-value"><b>Comments</b>: ${w}</p>
        <p class="card-value"><b>Downloads</b>: ${v}</p>       
        </div>
        </a>
        </li>`).join("");h.insertAdjacentHTML("beforeend",t),M.refresh()}function p(){h.innerHTML=""}function y(){g.classList.replace("is-hidden","is-show")}function b(){g.classList.replace("is-show","is-hidden")}function L(){f.classList.replace("is-hidden","is-show")}function l(){f.classList.replace("is-show","is-hidden")}let i=1,c="";const x=document.querySelector(".form");x.addEventListener("submit",B);f.addEventListener("click",E);async function B(r){if(r.preventDefault(),l(),r.target.elements["search-text"].value.trim()!==c&&(c=r.target.elements["search-text"].value.trim(),i=1),c!==""){y(),p();try{const{hits:t,totalHits:s}=await m(c,i);t.length===0?(l(),u.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"bottomRight"})):($(t),i*d<s?L():(l(),u.info({message:"We're sorry, but you've reached the end of search results.",position:"bottomRight"}))),b()}catch(t){console.log(t.message)}r.target.reset()}}async function E(){i+=1,l(),y();try{const{hits:r,totalHits:t}=await m(c,i);b(),p(r),i*d<t?L():(l(),u.info({message:"We're sorry, but you've reached the end of search results.",position:"bottomRight"}));const a=document.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy({left:0,top:a*2,behavior:"smooth"})}catch(r){console.log(r.message)}}
//# sourceMappingURL=index.js.map
